version: '3.9'
services:
#  nomad:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      network: host

#  mongo:
#    image: mongo
#    restart: always
#    ports:
#      - 27017:27017
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081

  zookeeper_container:
    image: library/zookeeper:3.6
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
#volumes:
#  mongodb_data_container:
