version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  zookeeper_container:
    image: library/zookeeper:latest
    restart: always
    hostname: zoo1
#    networks:
#      vpcbr:
#        ipv4_address: 10.5.0.2
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

volumes:
  mongodb_data_container:

#networks:
#  vpcbr:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.5.0.1/24