apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: kubernetes-dashboard

# eyJhbGciOiJSUzI1NiIsImtpZCI6ImRHN3BaeDB4ZGt3U3lGNVBKa1hsYW9wZ09ZUFVsVjBsSko5QWJlZkw0X2MifQeyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZC10b2tlbi05dG1iNiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjAxODM1ZmUxLTJhMzQtNDYzNS1iMzM3LWZlYmQ0ZDU4ZDg5YSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDprdWJlcm5ldGVzLWRhc2hib2FyZCJ9nLC5HBhigQBMSGJXFx3bqhcEgOWl_d97WmF1tpcSkvayZxzzI02gpPiiHuhBznM-atT12809Li4TSp5jUriVtJRUdPugVkHZtjisD0bapM-aa3UP6bNHvf2GniAi8MYoB9tigc8-g2vM6EvIQskydX7WJmB3e8ktsn5m6u5g9H2Er_YDXMOmjbRJJwgqyH3hUi6iQW7bMOKkrEQzGv0fBM3VRdLArKU4WYOsVbMgDQkMCQCGAAL7rzdpz7oie-EzmE7fN5bM0d4JS9g5kdbypHBbGbu9UHtlCxk0BNxsJNTlVbsgl6RlBsxZOtdmW_Rbkc_y4usAp-ye6pfRrrkR5w